services:
  - type: web
    name: avchatapp-backend
    runtime: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # Set this manually in Render dashboard
      - key: JWT_SECRET
        sync: false  # Set this manually in Render dashboard
      - key: FRONTEND_ORIGIN
        sync: false  # Set this to your frontend URL after deployment

  - type: web
    name: avchatapp-frontend
    runtime: static
    rootDir: Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        sync: false  # Set this to your backend URL after deployment
      - key: VITE_SOCKET_URL
        sync: false  # Set this to your backend URL after deployment
